import { Inter, Varela_Round } from "next/font/google";
import "./globals.css";

// Fonts
const inter = Inter({ subsets: ["latin"] });
const round = Varela_Round({ subsets: ["latin"], weight: "400" });

import { BackgroundProvider } from "@/provider/backgroundprovider/backgroundprovider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body suppressHydrationWarning={true} className={`${round.className}`}>
        <BackgroundProvider>{children}</BackgroundProvider>
      </body>
    </html>
  );
}
